message:
  tab:
    show: false
    lobby:
      header: "§3»§b»§f» %main_color%NOVA §f§lUHC §f«§b«§3«\n\n§8│ §7Joueurs: §f%players% §8| §7Serveur: §fUHC §8│\n"
      footer: "\n§8● §9/§fdiscord §8● §3/§fdoc"
    game:
      header: "§3»§b»§f» %main_color%NOVA §f§lUHC §f«§b«§3«\n\n§8│ §7Joueurs: §f%players% §8| §7Serveur: §fUHC §8│\n"
      footer: "\n§8● §9/§fdiscord §8● §3/§fdoc\n§cKills: §f%kills%"
    end:
      header: "§3»§b»§f» %main_color%NOVA §f§lUHC §f«§b«§3«\n\n§8│ §7Joueurs: §f%players% §8| §7Serveur: §fUHC §8│\n"
      footer: "\n§8● §9/§fdiscord §8● §3/§fdoc\n§cKills: §f%kills%\n%main_color%✦ Merci d'avoir participé ! ✦"


  scoreboard:
    lobby:
      title: "%main_color%§lNova UHC"
      lines:
        - ""
        - "§8┃ §fJoueurs: §b%players%§f/§b%slot%"
        - "§8┃ §fHost: %main_color%%host%"
        - ""
        - "<ip>"
    game:
      title: "%main_color%§lNova UHC"
      lines:
        - ""
        - "§8┃ §fJoueurs: %main_color%%players%§f/%main_color%%slot%"
        - "§8┃ §fDurée: %main_color%%timer%"
        - ""
        - "§8┃ §fBordure: %main_color%%border%"
        - ""
        - "§8┃ §fCentre: %main_color%%distance% %arrow%"
        - "§8┃ §fKill : %main_color%%kills%"
        - ""
        - "<ip>"
    end:
      title: "%main_color%§lNova UHC"
      lines:
        - ""
        - "§8┃ §fDurée totale: %main_color%%timer%"
        - "§8┃ §fVos éliminations: §c%kills%"
        - ""
        - "§8┃ §fFélicitations !"
        - ""
        - "<ip>"



timer:
  timer_before_start: 15
  combat: 30
