message:
  tab:
    show: false
    lobby:
      header: "§3»§b»§f» %main_color%NOVA §f§lUHC §f«§b«§3«\n\n§8│ §7Joueurs: §f%players% §8| §7Serveur: §fUHC §8│\n"
      footer: "\n§8● §9/§fdiscord §8● §3/§fdoc"
    game:
      header: "§3»§b»§f» %main_color%NOVA §f§lUHC §f«§b«§3«\n\n§8│ §7Joueurs: §f%players% §8| §7Serveur: §fUHC §8│\n"
      footer: "\n§8● §9/§fdiscord §8● §3/§fdoc\n§cKills: §f%kills%"
    end:
      header: "§3»§b»§f» %main_color%NOVA §f§lUHC §f«§b«§3«\n\n§8│ §7Joueurs: §f%players% §8| §7Serveur: §fUHC §8│\n"
      footer: "\n§8● §9/§fdiscord §8● §3/§fdoc\n§cKills: §f%kills%\n%main_color%✦ Merci d'avoir participé ! ✦"


  scoreboard:
    lobby:
      title: "%main_color%§lNova UHC"
      lines:
        - ""
        - "§f §5│ §fConnecté(s): §3%players%§f/%slot%"
        - "§f §5│ §fHost: §3%host%"
        - ""
        - "<ip>"
    game:
      title: "§f- %main_color%§lNova UHC §f-"
      lines:
        - ""
        - "§f §5│ §fConnecté(s): §3%players%§f/%slot%"
        - "§f §5│ §fDurée: §3%timer%"
        - ""
        - "§f §6│ §fPartie : "
        - "§f §f §8● §fTeam: %main_color%%team%"
        - "§f §f §8● §fKill : %main_color%%kills%"
        - ""
        - "§f §f §8● §fBordure: %main_color%%border%"
        - "§f §f §8● §fCentre: %main_color%%distance% %arrow%"
        - ""
        - "<ip>"


      title_role: "§f- %main_color%§lNova UHC §f-"
      lines_role:
        - ""
        - "§f §5│ §fConnecté(s): §3%players%§f/%slot%"
        - "§f §5│ §fDurée: §3%timer%"
        - ""
        - "§f §6│ §fPartie :"
        - "§f §f §8● §fRôle: %main_color%%role%"
        - "§f §f §8● §fKill : %main_color%%kills%"
        - ""
        - "§f §f §8● §fBordure: %main_color%%border%"
        - "§f §f §8● §fCentre: %main_color%%distance% %arrow%"
        - ""
        - "<ip>"
    end:
      title: "%main_color%§lNova UHC"
      lines:
        - ""
        - "§f §5│ §fConnecté(s): §3%players%§f/%slot%"
        - "§f §5│ §fDurée: §3%timer%"
        - ""
        - "§f §6│ §fPartie : "
        - "§f §f §8● §fRôle: %main_color%%role%"
        - "§f §f §8● §fKill : %main_color%%kills%"
        - ""
        - "<ip>"

timer:
  timer_before_start: 15
  combat: 30

staff:
  - "89daecd6-f9a7-4a2e-a8bf-a7d9294f074f"
