world_lobby:
  lobby_template: "lobby"
  lobby_target: "lob"
  location:
    spawn:
      world: "lob"
      x: 0
      y: 20
      z: 0
      yaw: 0
      pitch: 0
    rules:
      world: "lob"
      x: 39
      y: 61
      z: -13
      yaw: 0
      pitch: 0
arena_world:
  name: "arena"